<?php
$translations = [
    'en' => [
        'Bienvenido' => 'Welcome',
        'Correo electrónico' => 'Email',
        'Escribe tu usuario' => 'Enter your username',
        'Contraseña' => 'Password',
        'Escribe tu contraseña' => 'Enter your password',
        'Ingresar' => 'Sign in',
        'Salir' => 'Sign out',
        'Registrarse' => 'Register',
        'Olvidé mi contraseña' => 'Forgot my password',
        'Inicio' => 'Home',
        'Mi Perfil' => 'My Profile',
        'Documentos' => 'Documents',
        'Pagos' => 'Payments',
        'Pago' => 'Payment',
        'Revisa los documentos necesarios para tu viaje' => 'Review the documents required for your trip',
        'Pasaporte' => 'Passport',
        'Pasaporte 1' => 'Passport 1',
        'Pasaporte 2' => 'Passport 2',
        'Viajeros' => 'Travelers',
        'Reportes' => 'Reports',
        'Viajero' => 'Traveler',
        'Viajero:' => 'Traveler:',
        'Viajes' => 'Trips',
        'Viaje' => 'Trip',
        'Configuración' => 'Settings',
        'Faltante' => 'Missing',
        'Opcional' => 'Optional',
        'En revisión' => 'Under review',
        'Validado' => 'Validated',
        'validado' => 'validated',
        'Rechazado' => 'Rejected',
        'rechazado' => 'rejected',
        'Pendiente' => 'Pending',
        'Cancelado' => 'Canceled',
        'Documento' => 'Document',
        'Documento:' => 'Document:',
        'Primer pasaporte' => 'First passport',
        'Segundo pasaporte' => 'Second passport',
        'Depósito en efectivo' => 'Cash deposit',
        'Transferencia' => 'Bank transfer',
        'Admin' => 'Admin',
        'Editor' => 'Editor',
        'Consulta' => 'View only',
        'No definido' => 'Not defined',
        'Confirmado' => 'Confirmed',

        'El campo' => 'The field',
        'es obligatorio' => 'is required',
        'El correo electrónico no es válido' => 'The email address is not valid',
        'El correo del responsable no es válido' => 'The responsible person\'s email is not valid',
        'Las contraseñas no coinciden' => 'The passwords do not match',
        'La edad no es válida' => 'The age is not valid',
        'La fecha de nacimiento no es válida' => 'The date of birth is not valid',

        'Mi viaje' => 'My trip',
        'Estatus' => 'Status',
        'Estatus:' => 'Status:',
        'Consultar itinerario' => 'View itinerary',
        'Asistencia de viaje' => 'Travel assistance',
        'Número de asistencia de viaje' => 'Travel assistance number',
        'Número de asistencia de viaje:' => 'Travel assistance number:',
        'Documento de asistencia de viaje' => 'Travel assistance document',

        'Información importante' => 'Important information',
        'Viajeros que salen desde México' => 'Travelers departing from Mexico',
        'Viajeros que salen desde USA' => 'Travelers departing from the USA',
        'Avisos' => 'Notifications',

        'El pago cambió a: validated' => 'The payment changed to: validated',
        'El pago cambió a: ejected' => 'The payment changed to: rejected',
        'El pago cambió a: rejected' => 'The payment changed to: rejected',
        'Un pago fue creado.' => 'A payment was created.',
        'Un documento fue creado.' => 'A document was created.',

        'Costo total del viaje' => 'Total trip cost',
        'Pagado (validado):' => 'Paid (validated)',
        'Adeudo:' => 'Balance due',
        'Próximo pago sugerido el' => 'Next suggested payment on',
        'por una cantidad de' => 'for an amount of',
        'calculado dinámicamente' => 'calculated dynamically',

        'Fecha' => 'Date',
        'Monto' => 'Amount',
        'Monto:' => 'Amount:',
        'Estado' => 'Status',
        'Módulo de pagos' => 'Payment module',

        'No hay registros para mostrar' => 'No records to display',
        'No hay registros' => 'No records',
        'Regresar' => 'Back',
        'Observaciones:' => 'Notes:',
        'Pago en línea' => 'Online payment',
        'Tipo' => 'Type',
        'Tipo:' => 'Type:',
        'Se han pagado' => ' ',//vacío para que la segunda parte se complete mejor
        'de un total de' => 'paid out of a total of',
        'Historial de pagos' => 'Payment history',
        'Cantidad del' => 'Amount of the',
        'Cantidad del ' => 'Amount of the ',
        'costo del viaje' => 'trip cost',
        ' que desea pagar' => ' that you wish to pay',
        'que desea pagar' => 'that you wish to pay',
        'Tipo de cambio de' => 'Exchange rate for',
        'Pagar en línea con' => 'Pay online with',
        'ó subir un comprobante:' => 'or upload a payment receipt:',
        'Subir un comprobante:' => 'Upload a payment receipt:',
        'Cargar comprobante:' => 'Upload payment receipt:',
        'Enviar' => 'Send',
        'Tu pago mínimo en línea debe ser' => 'Your minimum online payment must be',

        'Fecha de creación:'=>'Creation date:',
        'Fecha de validación de pago:'=>'Payment validated on:',

        'Pago en Stripe de'=>'Stripe payment of',
        'fecha de tipo de cambio'=>'exchange rate date',

        'Documento subido el:' => 'Document uploaded on:',
        'Documento validado con fecha:' => 'Document validated on:',
        'Monto reconocido' => 'Recognized amount',

        'Nombre completo:' => 'Full name:',
        'Correo registrado:' => 'Registered email address:',
        'Fecha de nacimiento' => 'Date of birth',
        'Edad al momento de viajar' => 'Age at the time of travel',
        'Número de pasaporte con el que viaja' => 'Passport number used for travel',
        'Teléfono móvil personal' => 'Personal mobile phone',
        'Nombre del responsable del pago' => 'Name of person responsible for payment',
        'Correo electrónico del responsable del pago:' => 'E-mail of person responsible for payment:',
        'Teléfono móvil del responsable del pago' => 'Mobile phone of person responsible for payment',
        'Guardar' => 'Save',

        'Se guardaron los datos del usuario'=>'User data was saved',
        'Podrá realizar pagos del viaje cuando este se asigne.'=>'You will be able to make trip payments once the trip is assigned to you.',
        'Gracias. Estamos verificando su pago.'=>'Thank you. We are verifying your payment.',
        'Ha pagado completo el viaje, gracias.'=>'You have paid for the trip in full. Thank you.',
        'El usuario canceló el pago.'=>'The user canceled the payment.',
        'El monto es menor al pago mínimo necesario'=>'The amount is less than the minimum payment required',
        'El monto es mayor a lo que falta por pagar'=>'The amount is greater than the remaining balance',
        'El monto no puede ser cero'=>'The amount cannot be zero',
        'Recuperar contraseña'=>'Password recovery',
        'El usuario o contraseña no son correctos.'=>'The username or password is incorrect.',
        'Su cuenta estará bloqueada'=>'Your account will be locked for',
        'mins'=>'minutes',
        'Selecciona un archivo (el Pasaporte 1 es el obligatorio)'=>'Select a file (first passport is required)',
        'Selecciona un archivo'=>'Select a file',
        'El archivo excede el tamaño permitido (2 MB).'=>'The file exceeds the maximum allowed size (2 MB).',
        'Formato no permitido.'=>'Format not allowed.',
        'fue'=>'was',
        'Se actualizó el documento, notas originales:'=>'The document was updated, original notes:',
        'Pago validado'=>'Payment validated',
        'Se guardo el archivo correctamente.'=>'The file was saved successfully.',
        'El próximo pago sugerido es el'=>'The next suggested payment is',
        'y deberá pagar mínimo'=>'and you will need to pay a minimum of',
        'Recordatorio de pago'=>'Payment Reminder',
        'XXXX'=>'',


        'login' => 'Sign in',
        'email' => 'Email',
        'password' => 'Password',
        'save' => 'Save',
        'cancel' => 'Cancel',
        'logout' => 'Log out',
    ]
];

?>